# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresarFirmaStavkaRegistar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_kreiranja', models.DateTimeField(verbose_name='datum kreiranja')),
                ('dodatne_informacije', models.CharField(max_length=500)),
                ('telefon', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=200)),
                ('naziv', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdresarLiceStavkaRegistar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_kreiranja', models.DateTimeField(verbose_name='datum kreiranja')),
                ('dodatne_informacije', models.CharField(max_length=500)),
                ('telefon', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('ime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FirmaRegistar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv_broj', models.CharField(max_length=200)),
                ('id_broj', models.CharField(max_length=200)),
                ('telefon', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=200)),
                ('naziv', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KorisnikRegistar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('ime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_registracije', models.DateTimeField(verbose_name='datum registracije')),
                ('naziv', models.CharField(max_length=200)),
                ('user_django_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='korisnikregistar',
            name='korisnikregistar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserRegistar'),
        ),
        migrations.AddField(
            model_name='firmaregistar',
            name='korisnikregistar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserRegistar'),
        ),
        migrations.AddField(
            model_name='adresarlicestavkaregistar',
            name='korisnikregistar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserRegistar'),
        ),
        migrations.AddField(
            model_name='adresarfirmastavkaregistar',
            name='korisnikregistar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserRegistar'),
        ),
    ]
