# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistar',
            name='user_django_fk',
        ),
    ]
