# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160503_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='logo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='firma',
            name='opis',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='firma',
            name='slika_zaglavlje',
            field=models.CharField(default='', max_length=250),
        ),
    ]
