# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160504_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='uloga_fk',
        ),
    ]
