# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_firma_uloga_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='uloga_fk',
        ),
        migrations.AlterField(
            model_name='osoba',
            name='firma_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Firma'),
        ),
    ]
