# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20160504_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='firma_fk',
        ),
        migrations.AddField(
            model_name='uloga',
            name='firma_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uloga',
            name='user_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
