# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160504_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='admin_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
