# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160504_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='alias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='grad_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Grad'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='slika_zaglavlje',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
