# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160510_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='datum_registracije',
        ),
    ]
