# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_osoba_datum_registracije'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=250, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='slika',
            field=models.ImageField(blank=True, default='', max_length=250, null=True, upload_to=b''),
        ),
    ]
