# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160531_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='slika_zaglavlje',
        ),
    ]
