# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_firma_slika_zaglavlje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=250, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='slika',
            field=models.ImageField(blank=True, default='', max_length=250, null=True, upload_to='slika/'),
        ),
    ]
