# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160524_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='myphoto/')),
            ],
        ),
        migrations.RemoveField(
            model_name='logo',
            name='vlasnik',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
