# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160531_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontakt',
            name='kategorija',
        ),
        migrations.AddField(
            model_name='kontakt',
            name='osoba_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Osoba'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='firma_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Firma'),
        ),
    ]
