# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_myphoto_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(max_length=255, null=True, upload_to='myphoto/')),
            ],
        ),
        migrations.RemoveField(
            model_name='myphoto',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='slika_zaglavlje',
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='slika',
        ),
        migrations.DeleteModel(
            name='MyPhoto',
        ),
        migrations.AddField(
            model_name='slika',
            name='firma_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Firma'),
        ),
        migrations.AddField(
            model_name='slika',
            name='osoba_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Osoba'),
        ),
    ]
